# Variables

# Compilador
CC = gcc 

# Flags

CFLAGS = -Wall -Werror -Wextra -pedantic -std=c99 -g

# Objetivo o nombre del ejecutable

all: reader

# Reglas

compila:
    $(CC) $(CFLAGS) -o reader main.c
